// Generated by contract/script/export_abis.py. Do not edit.
export const aggregatorV3Abi = [
 {
  "type": "function",
  "name": "decimals",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint8",
    "internalType": "uint8"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getRoundData",
  "inputs": [
   {
    "name": "roundId",
    "type": "uint80",
    "internalType": "uint80"
   }
  ],
  "outputs": [
   {
    "name": "roundId_",
    "type": "uint80",
    "internalType": "uint80"
   },
   {
    "name": "answer",
    "type": "int256",
    "internalType": "int256"
   },
   {
    "name": "startedAt",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "updatedAt",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "answeredInRound",
    "type": "uint80",
    "internalType": "uint80"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "latestRoundData",
  "inputs": [],
  "outputs": [
   {
    "name": "roundId",
    "type": "uint80",
    "internalType": "uint80"
   },
   {
    "name": "answer",
    "type": "int256",
    "internalType": "int256"
   },
   {
    "name": "startedAt",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "updatedAt",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "answeredInRound",
    "type": "uint80",
    "internalType": "uint80"
   }
  ],
  "stateMutability": "view"
 }
] as const;
