// Generated by contract/script/export_abis.py. Do not edit.
export const optaraConfigAbi = [
 {
  "type": "constructor",
  "inputs": [
   {
    "name": "governance",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "CONFIG_ROLE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "DEFAULT_ADMIN_ROLE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "GLOBAL_SCOPE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "GOVERNANCE_ROLE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "HARD_MAX_GROUPS_PER_ACCOUNT",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "HARD_MAX_SERIES_PER_ACCOUNT",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "HARD_MAX_SERIES_PER_GROUP",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_BUFFER_BPS",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint16",
    "internalType": "uint16"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_PRICE_WAD",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "ORACLE_CONFIG_ROLE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "PAUSER_ROLE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "SERIES_CREATOR_ROLE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "UNPAUSER_ROLE",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "approveAsset",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "symbol",
    "type": "string",
    "internalType": "string"
   },
   {
    "name": "bufferBps",
    "type": "uint16",
    "internalType": "uint16"
   },
   {
    "name": "fixedBufferNative",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "approvePair",
  "inputs": [
   {
    "name": "underlying",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "bounds",
    "type": "tuple",
    "internalType": "struct SeriesBounds",
    "components": [
     {
      "name": "minStrikeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maxStrikeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "minCapWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maxCapWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "minContractSizeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maxContractSizeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "minTimeToExpiry",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxTimeToExpiry",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "quantityIncrement",
      "type": "uint256",
      "internalType": "uint256"
     }
    ]
   },
   {
    "name": "seriesExposureLimitN",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "pairExposureLimitN",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "pairId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "approveUnderlying",
  "inputs": [
   {
    "name": "underlying",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "symbol",
    "type": "string",
    "internalType": "string"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "assetInfo",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "known",
    "type": "bool",
    "internalType": "bool"
   },
   {
    "name": "newRiskEnabled",
    "type": "bool",
    "internalType": "bool"
   },
   {
    "name": "decimals",
    "type": "uint8",
    "internalType": "uint8"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "assetScope",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "pure"
 },
 {
  "type": "function",
  "name": "assetSymbol",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "string",
    "internalType": "string"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "bufferDefaults",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "bufferBps",
    "type": "uint16",
    "internalType": "uint16"
   },
   {
    "name": "fixedBufferNative",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "exposureLimits",
  "inputs": [
   {
    "name": "pairId",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "oracleConfigId",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "seriesLimitN",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "pairLimitN",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "oracleLimitN",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "assetLimitN",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getRoleAdmin",
  "inputs": [
   {
    "name": "role",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getRoleMember",
  "inputs": [
   {
    "name": "role",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "index",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getRoleMemberCount",
  "inputs": [
   {
    "name": "role",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getRoleMembers",
  "inputs": [
   {
    "name": "role",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "address[]",
    "internalType": "address[]"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "grantRole",
  "inputs": [
   {
    "name": "role",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "account",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "hasRole",
  "inputs": [
   {
    "name": "role",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "account",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "isPaused",
  "inputs": [
   {
    "name": "action",
    "type": "uint256",
    "internalType": "uint256"
   },
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "oracleConfigId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pairIdOf",
  "inputs": [
   {
    "name": "underlying",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "pure"
 },
 {
  "type": "function",
  "name": "pairInfo",
  "inputs": [
   {
    "name": "pairId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "status",
    "type": "uint8",
    "internalType": "enum PairStatus"
   },
   {
    "name": "underlying",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "pause",
  "inputs": [
   {
    "name": "scope",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "bits",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "pausedBits",
  "inputs": [
   {
    "name": "scope",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "positionLimits",
  "inputs": [],
  "outputs": [
   {
    "name": "maxSeriesPerGroup",
    "type": "uint32",
    "internalType": "uint32"
   },
   {
    "name": "maxGroupsPerAccount",
    "type": "uint32",
    "internalType": "uint32"
   },
   {
    "name": "maxSeriesPerAccount",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "renounceRole",
  "inputs": [
   {
    "name": "role",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "callerConfirmation",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "revokeRole",
  "inputs": [
   {
    "name": "role",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "account",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "seriesBounds",
  "inputs": [
   {
    "name": "pairId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct SeriesBounds",
    "components": [
     {
      "name": "minStrikeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maxStrikeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "minCapWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maxCapWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "minContractSizeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maxContractSizeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "minTimeToExpiry",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxTimeToExpiry",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "quantityIncrement",
      "type": "uint256",
      "internalType": "uint256"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "setAssetBufferDefaults",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "bufferBps",
    "type": "uint16",
    "internalType": "uint16"
   },
   {
    "name": "fixedBufferNative",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setAssetNewRiskEnabled",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "enabled",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setExposureLimit",
  "inputs": [
   {
    "name": "scope",
    "type": "uint8",
    "internalType": "enum ExposureScope"
   },
   {
    "name": "key",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "newLimitN",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setPairStatus",
  "inputs": [
   {
    "name": "pairId",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "newStatus",
    "type": "uint8",
    "internalType": "enum PairStatus"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setPositionLimits",
  "inputs": [
   {
    "name": "maxSeriesPerGroup",
    "type": "uint32",
    "internalType": "uint32"
   },
   {
    "name": "maxGroupsPerAccount",
    "type": "uint32",
    "internalType": "uint32"
   },
   {
    "name": "maxSeriesPerAccount",
    "type": "uint32",
    "internalType": "uint32"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setSeriesBounds",
  "inputs": [
   {
    "name": "pairId",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "bounds",
    "type": "tuple",
    "internalType": "struct SeriesBounds",
    "components": [
     {
      "name": "minStrikeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maxStrikeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "minCapWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maxCapWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "minContractSizeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maxContractSizeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "minTimeToExpiry",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxTimeToExpiry",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "quantityIncrement",
      "type": "uint256",
      "internalType": "uint256"
     }
    ]
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setUnderlyingApproved",
  "inputs": [
   {
    "name": "underlying",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "approved",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "supportsInterface",
  "inputs": [
   {
    "name": "interfaceId",
    "type": "bytes4",
    "internalType": "bytes4"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "underlyingInfo",
  "inputs": [
   {
    "name": "underlying",
    "type": "address",
    "internalType": "address"
   }
  ],
  "outputs": [
   {
    "name": "approved",
    "type": "bool",
    "internalType": "bool"
   },
   {
    "name": "symbol",
    "type": "string",
    "internalType": "string"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "unpause",
  "inputs": [
   {
    "name": "scope",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "bits",
    "type": "uint256",
    "internalType": "uint256"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "event",
  "name": "AssetApproved",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "decimals",
    "type": "uint8",
    "indexed": false,
    "internalType": "uint8"
   },
   {
    "name": "symbol",
    "type": "string",
    "indexed": false,
    "internalType": "string"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "AssetDisabled",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "caller",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "AssetReenabled",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "caller",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "BufferDefaultsChanged",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "bufferBps",
    "type": "uint16",
    "indexed": false,
    "internalType": "uint16"
   },
   {
    "name": "fixedBufferNative",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "ExposureLimitChanged",
  "inputs": [
   {
    "name": "scope",
    "type": "uint8",
    "indexed": true,
    "internalType": "enum ExposureScope"
   },
   {
    "name": "key",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "oldLimitN",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "newLimitN",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "PairApproved",
  "inputs": [
   {
    "name": "pairId",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "underlying",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "asset",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "PairDisabled",
  "inputs": [
   {
    "name": "pairId",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "newStatus",
    "type": "uint8",
    "indexed": false,
    "internalType": "enum PairStatus"
   },
   {
    "name": "caller",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "PairEnabled",
  "inputs": [
   {
    "name": "pairId",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "caller",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "PauseStateChanged",
  "inputs": [
   {
    "name": "scope",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "oldBits",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "newBits",
    "type": "uint256",
    "indexed": false,
    "internalType": "uint256"
   },
   {
    "name": "caller",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "PositionLimitsChanged",
  "inputs": [
   {
    "name": "maxSeriesPerGroup",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   },
   {
    "name": "maxGroupsPerAccount",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   },
   {
    "name": "maxSeriesPerAccount",
    "type": "uint32",
    "indexed": false,
    "internalType": "uint32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "RoleAdminChanged",
  "inputs": [
   {
    "name": "role",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "previousAdminRole",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "newAdminRole",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "RoleGranted",
  "inputs": [
   {
    "name": "role",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "account",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "sender",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "RoleRevoked",
  "inputs": [
   {
    "name": "role",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "account",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "sender",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "SeriesBoundsChanged",
  "inputs": [
   {
    "name": "pairId",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "bounds",
    "type": "tuple",
    "indexed": false,
    "internalType": "struct SeriesBounds",
    "components": [
     {
      "name": "minStrikeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maxStrikeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "minCapWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maxCapWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "minContractSizeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "maxContractSizeWad",
      "type": "uint256",
      "internalType": "uint256"
     },
     {
      "name": "minTimeToExpiry",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxTimeToExpiry",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "quantityIncrement",
      "type": "uint256",
      "internalType": "uint256"
     }
    ]
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "UnderlyingApproved",
  "inputs": [
   {
    "name": "underlying",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "symbol",
    "type": "string",
    "indexed": false,
    "internalType": "string"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "UnderlyingStatusChanged",
  "inputs": [
   {
    "name": "underlying",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "approved",
    "type": "bool",
    "indexed": false,
    "internalType": "bool"
   },
   {
    "name": "caller",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "error",
  "name": "AccessControlBadConfirmation",
  "inputs": []
 },
 {
  "type": "error",
  "name": "AccessControlUnauthorizedAccount",
  "inputs": [
   {
    "name": "account",
    "type": "address",
    "internalType": "address"
   },
   {
    "name": "neededRole",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ]
 },
 {
  "type": "error",
  "name": "AssetAlreadyKnown",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   }
  ]
 },
 {
  "type": "error",
  "name": "EmptySymbol",
  "inputs": []
 },
 {
  "type": "error",
  "name": "InvalidBounds",
  "inputs": []
 },
 {
  "type": "error",
  "name": "InvalidBuffer",
  "inputs": []
 },
 {
  "type": "error",
  "name": "InvalidLimit",
  "inputs": []
 },
 {
  "type": "error",
  "name": "InvalidPairTransition",
  "inputs": [
   {
    "name": "from",
    "type": "uint8",
    "internalType": "enum PairStatus"
   },
   {
    "name": "to",
    "type": "uint8",
    "internalType": "enum PairStatus"
   }
  ]
 },
 {
  "type": "error",
  "name": "InvalidPauseBits",
  "inputs": []
 },
 {
  "type": "error",
  "name": "LastGovernanceMember",
  "inputs": []
 },
 {
  "type": "error",
  "name": "NotAuthorized",
  "inputs": [
   {
    "name": "caller",
    "type": "address",
    "internalType": "address"
   }
  ]
 },
 {
  "type": "error",
  "name": "PairAlreadyApproved",
  "inputs": [
   {
    "name": "pairId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ]
 },
 {
  "type": "error",
  "name": "UnderlyingEqualsAsset",
  "inputs": []
 },
 {
  "type": "error",
  "name": "UnderlyingNotApproved",
  "inputs": [
   {
    "name": "underlying",
    "type": "address",
    "internalType": "address"
   }
  ]
 },
 {
  "type": "error",
  "name": "UnknownAsset",
  "inputs": [
   {
    "name": "asset",
    "type": "address",
    "internalType": "address"
   }
  ]
 },
 {
  "type": "error",
  "name": "UnknownPair",
  "inputs": [
   {
    "name": "pairId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ]
 },
 {
  "type": "error",
  "name": "UnsupportedDecimals",
  "inputs": [
   {
    "name": "decimals",
    "type": "uint8",
    "internalType": "uint8"
   }
  ]
 },
 {
  "type": "error",
  "name": "ZeroAddress",
  "inputs": []
 }
] as const;
