// Generated by contract/script/export_abis.py. Do not edit.
export const oracleRegistryAbi = [
 {
  "type": "constructor",
  "inputs": [
   {
    "name": "config_",
    "type": "address",
    "internalType": "contract IOptaraConfig"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "MAX_FINALIZATION_DELAY",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "MAX_OFFSET",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "adapterOf",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "address"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "config",
  "inputs": [],
  "outputs": [
   {
    "name": "",
    "type": "address",
    "internalType": "contract IOptaraConfig"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "finalizationDelays",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "minDelay",
    "type": "uint64",
    "internalType": "uint64"
   },
   {
    "name": "maxDelay",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "getConfig",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "tuple",
    "internalType": "struct OracleConfig",
    "components": [
     {
      "name": "underlying",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "settlementAsset",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "adapter",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "observationStartOffset",
      "type": "int64",
      "internalType": "int64"
     },
     {
      "name": "observationEndOffset",
      "type": "int64",
      "internalType": "int64"
     },
     {
      "name": "minFinalizationDelay",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxFinalizationDelay",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "ruleVersion",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "sourceParams",
      "type": "bytes",
      "internalType": "bytes"
     }
    ]
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "isApprovedForNewRisk",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "bool",
    "internalType": "bool"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "observationWindow",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "expiry",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "outputs": [
   {
    "name": "start",
    "type": "uint64",
    "internalType": "uint64"
   },
   {
    "name": "end",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "registerConfig",
  "inputs": [
   {
    "name": "cfg",
    "type": "tuple",
    "internalType": "struct OracleConfig",
    "components": [
     {
      "name": "underlying",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "settlementAsset",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "adapter",
      "type": "address",
      "internalType": "address"
     },
     {
      "name": "observationStartOffset",
      "type": "int64",
      "internalType": "int64"
     },
     {
      "name": "observationEndOffset",
      "type": "int64",
      "internalType": "int64"
     },
     {
      "name": "minFinalizationDelay",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "maxFinalizationDelay",
      "type": "uint64",
      "internalType": "uint64"
     },
     {
      "name": "ruleVersion",
      "type": "bytes32",
      "internalType": "bytes32"
     },
     {
      "name": "sourceParams",
      "type": "bytes",
      "internalType": "bytes"
     }
    ]
   }
  ],
  "outputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "setStatus",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "newStatus",
    "type": "uint8",
    "internalType": "enum OracleConfigStatus"
   }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
 },
 {
  "type": "function",
  "name": "statusOf",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ],
  "outputs": [
   {
    "name": "",
    "type": "uint8",
    "internalType": "enum OracleConfigStatus"
   }
  ],
  "stateMutability": "view"
 },
 {
  "type": "function",
  "name": "validateSeriesExpiry",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "internalType": "bytes32"
   },
   {
    "name": "expiry",
    "type": "uint64",
    "internalType": "uint64"
   }
  ],
  "outputs": [],
  "stateMutability": "view"
 },
 {
  "type": "event",
  "name": "OracleConfigApproved",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "underlying",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "settlementAsset",
    "type": "address",
    "indexed": true,
    "internalType": "address"
   },
   {
    "name": "adapter",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "OracleConfigDisabled",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "newStatus",
    "type": "uint8",
    "indexed": false,
    "internalType": "enum OracleConfigStatus"
   },
   {
    "name": "caller",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "event",
  "name": "OracleConfigStatusChanged",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "indexed": true,
    "internalType": "bytes32"
   },
   {
    "name": "oldStatus",
    "type": "uint8",
    "indexed": false,
    "internalType": "enum OracleConfigStatus"
   },
   {
    "name": "newStatus",
    "type": "uint8",
    "indexed": false,
    "internalType": "enum OracleConfigStatus"
   },
   {
    "name": "caller",
    "type": "address",
    "indexed": false,
    "internalType": "address"
   }
  ],
  "anonymous": false
 },
 {
  "type": "error",
  "name": "ConfigAlreadyRegistered",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ]
 },
 {
  "type": "error",
  "name": "InvalidConfig",
  "inputs": [
   {
    "name": "reason",
    "type": "string",
    "internalType": "string"
   }
  ]
 },
 {
  "type": "error",
  "name": "InvalidObservationTime",
  "inputs": []
 },
 {
  "type": "error",
  "name": "InvalidStatusTransition",
  "inputs": [
   {
    "name": "from",
    "type": "uint8",
    "internalType": "enum OracleConfigStatus"
   },
   {
    "name": "to",
    "type": "uint8",
    "internalType": "enum OracleConfigStatus"
   }
  ]
 },
 {
  "type": "error",
  "name": "NotAuthorized",
  "inputs": [
   {
    "name": "caller",
    "type": "address",
    "internalType": "address"
   }
  ]
 },
 {
  "type": "error",
  "name": "UnknownConfig",
  "inputs": [
   {
    "name": "configId",
    "type": "bytes32",
    "internalType": "bytes32"
   }
  ]
 }
] as const;
