// Generates every Optara brand asset as SVG (brand/README.md). Rasterize with render.mjs.
//   cd brand/source && npm install && node build.mjs && node render.mjs
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import opentype from "opentype.js";

const require = createRequire(import.meta.url);
const OUT = join(dirname(fileURLToPath(import.meta.url)), "..");
const font = (w) =>
  opentype.parse(
    readFileSync(require.resolve(`@fontsource/space-grotesk/files/space-grotesk-latin-${w}-normal.woff`)).buffer,
  );
const BOLD = font(700);
const MEDIUM = font(500);

// ------------------------------------------------------------------------------------------------ palette
// Monad's published brand palette as the foundation, plus three Optara colours: mint for calls and the
// uncapped ray, ember for the strike (Kuru's "exploding star" energy), lavender for highlights.
export const C = {
  night: "#0d0024", // deepest background, a darker Monad Blue
  monadBlue: "#200052",
  monadPurple: "#836ef9",
  monadBerry: "#a0055d",
  offWhite: "#fbfaf9",
  black: "#0e100f",
  mint: "#5cf2c4",
  ember: "#ff7a3d",
  lavender: "#c3b6ff",
  violet: "#4a2bd0", // purple shadow, the disc's lower edge
  mutedOnDark: "#b3a9d9",
  mutedOnLight: "#5a4f7d",
  mintOnLight: "#00a67a",
};
writeFileSync(join(OUT, "tokens.json"), JSON.stringify(C, null, 2) + "\n");
writeFileSync(
  join(OUT, "tokens.css"),
  `/* Optara brand tokens (generated by brand/source/build.mjs). */\n:root {\n${Object.entries(C)
    .map(([k, v]) => `  --optara-${k.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase())}: ${v};`)
    .join("\n")}\n  --optara-breakout: linear-gradient(90deg, ${C.monadBerry}, ${C.monadPurple} 50%, ${C.mint});\n  --optara-strike: linear-gradient(90deg, ${C.monadBerry}, ${C.ember});\n}\n`,
);

const write = (rel, s) => {
  const p = join(OUT, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, s.trim() + "\n");
};
const svg = (w, h, body) =>
  `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${body}</svg>`;

// ------------------------------------------------------------------------------------------------ the mark
// One coin (Monad's coin-like counter): calls above in purple, puts below in berry. A call payoff slices it, flat
// below the strike, a kink, then a ray that breaks out of the coin: uncapped. The ember dot is the strike, where the
// trade happens. Drawn in a 64 box, optically centred.
const DISC = { cx: 31, cy: 34, r: 21 };
const STRIKE = [29, 41];
const PAY = `M6 41 H${STRIKE[0]} L57 13`;
const CUT = 11;
const LINE = 5.5;
const DOT = 4.6;
// The lower segment's chord sits at the strike level, so its arc is the circle below y = 41.
const segY = STRIKE[1];
const segDx = Math.sqrt(DISC.r ** 2 - (segY - DISC.cy) ** 2);
const lowerSeg = `M${(DISC.cx - segDx).toFixed(3)} ${segY} H${(DISC.cx + segDx).toFixed(3)} A${DISC.r} ${DISC.r} 0 0 1 ${(DISC.cx - segDx).toFixed(3)} ${segY}Z`;

/**
 * The mark's body in a 64 box. theme: dark (on dark grounds), light (on light grounds), white | black (one colour).
 */
function mark(id, theme = "dark") {
  const cut = `<mask id="${id}-cut" maskUnits="userSpaceOnUse" x="0" y="0" width="64" height="64">
      <rect width="64" height="64" fill="#fff"/>
      <path d="${PAY}" stroke="#000" stroke-width="${CUT}" fill="none" stroke-linejoin="round" stroke-linecap="round"/></mask>`;
  const wrap = (b) => `<g transform="translate(0.5 -0.6)">${b}</g>`;
  if (theme === "white" || theme === "black") {
    const c = theme === "white" ? C.offWhite : C.night;
    return wrap(`<defs>${cut}</defs>
      <circle cx="${DISC.cx}" cy="${DISC.cy}" r="${DISC.r}" fill="${c}" mask="url(#${id}-cut)"/>
      <path d="${PAY}" stroke="${c}" stroke-width="${LINE}" fill="none" stroke-linecap="round" stroke-linejoin="round"/>`);
  }
  const lineFrom = theme === "dark" ? C.offWhite : C.monadBlue;
  const lineTo = theme === "dark" ? C.mint : C.mintOnLight;
  return wrap(`<defs>${cut}
    <linearGradient id="${id}-call" x1="12" y1="54" x2="50" y2="14" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="${C.violet}"/><stop offset="0.5" stop-color="${C.monadPurple}"/><stop offset="1" stop-color="${C.lavender}"/></linearGradient>
    <linearGradient id="${id}-put" x1="10" y1="56" x2="52" y2="34" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="${C.monadBerry}"/><stop offset="1" stop-color="#6a2bd9"/></linearGradient>
    <linearGradient id="${id}-ray" x1="${STRIKE[0]}" y1="${STRIKE[1]}" x2="57" y2="13" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="${lineFrom}"/><stop offset="1" stop-color="${lineTo}"/></linearGradient>
  </defs>
  <g mask="url(#${id}-cut)">
    <circle cx="${DISC.cx}" cy="${DISC.cy}" r="${DISC.r}" fill="url(#${id}-call)"/>
    <path d="${lowerSeg}" fill="url(#${id}-put)"/>
  </g>
  <path d="${PAY}" stroke="url(#${id}-ray)" stroke-width="${LINE}" fill="none" stroke-linecap="round" stroke-linejoin="round"/>
  <circle cx="${STRIKE[0]}" cy="${STRIKE[1]}" r="${DOT}" fill="${C.ember}"/>`);
}
/** The mark placed at (x, y) with size s (px). */
const markAt = (id, x, y, s, theme = "dark") => `<g transform="translate(${x} ${y}) scale(${s / 64})">${mark(id, theme)}</g>`;

/** Night ground with a lifted purple centre, used by icons and avatars. */
const nightGround = (id, w, h, cy = 0.4) => `<defs><radialGradient id="${id}-ng" cx="0.5" cy="${cy}" r="0.75">
    <stop offset="0" stop-color="#2d0a78"/><stop offset="0.55" stop-color="${C.monadBlue}"/><stop offset="1" stop-color="${C.night}"/></radialGradient></defs>
  <rect width="${w}" height="${h}" fill="url(#${id}-ng)"/>`;

/** App icon: rounded tile. */
function appIcon(size, { radius = 0.235, scale = 0.74, id = "ai" } = {}) {
  const rx = size * radius;
  const m = size * scale;
  return svg(
    size,
    size,
    `<defs><clipPath id="${id}-clip"><rect width="${size}" height="${size}" rx="${rx}"/></clipPath></defs>
    <g clip-path="url(#${id}-clip)">${nightGround(id, size, size)}
      <rect x="0.5" y="0.5" width="${size - 1}" height="${size - 1}" rx="${rx}" fill="none" stroke="#fff" stroke-opacity="0.1"/>
      ${markAt(`${id}-m`, (size - m) / 2, (size - m) / 2, m)}</g>`,
  );
}
/** Full-bleed square for profile pictures (platforms crop to a circle). */
function avatar(size, id = "av") {
  const m = size * 0.62;
  return svg(size, size, `${nightGround(id, size, size, 0.45)}${markAt(`${id}-m`, (size - m) / 2, (size - m) / 2, m)}`);
}

// ------------------------------------------------------------------------------------------------ type
/** Text as outlined paths. Returns {d, width}. */
function text(f, s, size, x, y, tracking = 0) {
  let d = "";
  let cx = x;
  const k = size / f.unitsPerEm;
  const gs = f.stringToGlyphs(s);
  gs.forEach((g, i) => {
    d += g.getPath(cx, y, size).toPathData(2);
    cx += g.advanceWidth * k;
    if (i < gs.length - 1) cx += f.getKerningValue(g, gs[i + 1]) * k + tracking * size;
  });
  return { d, width: cx - x };
}
const WORD_TRACK = -0.025;
const wordWidth = (size) => text(BOLD, "optara", size, 0, 0, WORD_TRACK).width;

/** Horizontal lockup. theme dark | light | white | black. */
function lockup(theme, { tag = false, id = "lk" } = {}) {
  const ink = { dark: C.offWhite, light: C.monadBlue, white: C.offWhite, black: C.night }[theme];
  const muted = theme === "light" || theme === "black" ? C.mutedOnLight : C.mutedOnDark;
  const markTheme = theme === "dark" || theme === "light" ? theme : theme;
  const size = 50;
  const wx = 76;
  const word = text(BOLD, "optara", size, wx, 47, WORD_TRACK);
  const t = tag ? text(MEDIUM, "OPTIONS ON MONAD", 11, wx + 2, 72, 0.16) : null;
  const W = Math.ceil(wx + Math.max(word.width, t ? t.width : 0) + 4);
  return svg(W, tag ? 78 : 64, `${mark(id, markTheme)}<path d="${word.d}" fill="${ink}"/>${t ? `<path d="${t.d}" fill="${muted}"/>` : ""}`);
}
function stacked(theme, id = "st") {
  const ink = theme === "dark" ? C.offWhite : C.monadBlue;
  const size = 42;
  const ww = wordWidth(size);
  const W = Math.ceil(Math.max(96, ww) + 16);
  const word = text(BOLD, "optara", size, (W - ww) / 2, 128, WORD_TRACK);
  return svg(W, 140, `${markAt(id, (W - 88) / 2, 0, 88, theme)}<path d="${word.d}" fill="${ink}"/>`);
}

// ------------------------------------------------------------------------------------------------ backgrounds
// Black-76 values (zero rates) for a fan of times to expiry: call curves rise to the right, put curves to the left,
// both hardening into the payoff as expiry nears and meeting at the strike. Real option math, drawn.
const erf = (x) => {
  const s = Math.sign(x);
  x = Math.abs(x);
  const t = 1 / (1 + 0.3275911 * x);
  return s * (1 - ((((1.061405429 * t - 1.453152027) * t + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t * Math.exp(-x * x));
};
const N = (x) => 0.5 * (1 + erf(x / Math.SQRT2));
function b76(F, K, sigT, put) {
  if (sigT < 1e-9) return Math.max(put ? K - F : F - K, 0);
  const d1 = (Math.log(F / K) + 0.5 * sigT * sigT) / sigT;
  const c = F * N(d1) - K * N(d1 - sigT);
  return put ? c - (F - K) : c;
}

/**
 * A fan of value curves across [x0, x1]. Spot F = 1 + (x − sx) / k, so the strike sits at sx; value rises from baseY at
 * yScale px per unit of strike. put mirrors the payoff. Gradients: `${id}-c` / `${id}-p` (fan), `-chot` / `-phot` (expiry).
 */
function fan({ id, x0, x1, sx, k, baseY, yScale, put = false, count = 20, stroke = 1.4, opacity = 1, maxSig = 1.6 }) {
  const g = put ? "p" : "c";
  let out = "";
  let hot = "";
  for (let i = 0; i < count; i++) {
    const f = i / (count - 1);
    const sigT = maxSig * (1 - f) ** 1.6;
    const pts = [];
    for (let j = 0; j <= 240; j++) {
      const x = x0 + ((x1 - x0) * j) / 240;
      const F = Math.max(0.02, 1 + (x - sx) / k); // the strike (F = 1) always lands on sx
      pts.push(`${x.toFixed(1)} ${(baseY - b76(F, 1, sigT, put) * yScale).toFixed(1)}`);
    }
    const d = `M${pts.join(" L")}`;
    if (i === count - 1) {
      hot = `<path d="${d}" fill="none" stroke="url(#${id}-${g}hot)" stroke-width="${stroke * 2.4}" stroke-linecap="round" stroke-linejoin="round"/>`;
    } else {
      const op = ((0.1 + 0.45 * f ** 1.4) * opacity).toFixed(3);
      out += `<path d="${d}" fill="none" stroke="url(#${id}-${g})" stroke-opacity="${op}" stroke-width="${stroke}" stroke-linecap="round" stroke-linejoin="round"/>`;
    }
  }
  const hotOp = opacity.toFixed(2);
  return `<g>${out}</g><g opacity="${(0.6 * opacity).toFixed(2)}" filter="url(#${id}-glow)">${hot}</g><g opacity="${hotOp}">${hot}</g>`;
}

/** The strike: an ember point with a soft burst of rays (Kuru's exploding star, kept quiet). */
function strikeBurst(id, x, y, r, rays = 28) {
  let lines = "";
  for (let i = 0; i < rays; i++) {
    const a = (i / rays) * Math.PI * 2 + 0.11;
    const len = r * (i % 3 === 0 ? 5.2 : i % 2 === 0 ? 3.6 : 2.6);
    lines += `<line x1="${(x + Math.cos(a) * r * 1.6).toFixed(1)}" y1="${(y + Math.sin(a) * r * 1.6).toFixed(1)}" x2="${(x + Math.cos(a) * len).toFixed(1)}" y2="${(y + Math.sin(a) * len).toFixed(1)}"/>`;
  }
  return `<g stroke="url(#${id}-burst)" stroke-width="${Math.max(1, r * 0.12)}" stroke-linecap="round" opacity="0.55">${lines}</g>
    <circle cx="${x}" cy="${y}" r="${r * 4}" fill="url(#${id}-emberglow)"/>
    <circle cx="${x}" cy="${y}" r="${r}" fill="${C.ember}"/>
    <circle cx="${x}" cy="${y}" r="${r * 0.42}" fill="#ffd2b8"/>`;
}

/** Ground for full-bleed art: night, aurora glows, faint grid, grain. Defines every gradient the art uses. */
function ground(W, H, id, { aurora = [0.75, 0.15], strike = [0.5, 0.8], grid = 56 } = {}) {
  const [sx, sy] = strike;
  return `<defs>
    <linearGradient id="${id}-base" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${C.night}"/><stop offset="0.6" stop-color="#150038"/><stop offset="1" stop-color="${C.night}"/></linearGradient>
    <radialGradient id="${id}-a1" cx="${aurora[0]}" cy="${aurora[1]}" r="0.6"><stop offset="0" stop-color="${C.monadPurple}" stop-opacity="0.42"/><stop offset="1" stop-color="${C.monadPurple}" stop-opacity="0"/></radialGradient>
    <radialGradient id="${id}-a2" cx="0.05" cy="1" r="0.6"><stop offset="0" stop-color="${C.monadBerry}" stop-opacity="0.42"/><stop offset="1" stop-color="${C.monadBerry}" stop-opacity="0"/></radialGradient>
    <radialGradient id="${id}-a3" cx="1" cy="0.75" r="0.5"><stop offset="0" stop-color="${C.mint}" stop-opacity="0.12"/><stop offset="1" stop-color="${C.mint}" stop-opacity="0"/></radialGradient>
    <radialGradient id="${id}-a4" cx="${sx}" cy="${sy}" r="0.3"><stop offset="0" stop-color="${C.ember}" stop-opacity="0.16"/><stop offset="1" stop-color="${C.ember}" stop-opacity="0"/></radialGradient>
    <pattern id="${id}-grid" width="${grid}" height="${grid}" patternUnits="userSpaceOnUse"><path d="M${grid} 0H0V${grid}" fill="none" stroke="#fff" stroke-opacity="0.05"/></pattern>
    <radialGradient id="${id}-gm" cx="${sx}" cy="${sy}" r="0.8"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#000"/></radialGradient>
    <mask id="${id}-gridmask"><rect width="${W}" height="${H}" fill="url(#${id}-gm)"/></mask>
    <filter id="${id}-grain" x="0" y="0" width="100%" height="100%"><feTurbulence type="fractalNoise" baseFrequency="0.85" numOctaves="2" stitchTiles="stitch"/>
      <feColorMatrix values="0 0 0 0 1  0 0 0 0 1  0 0 0 0 1  0 0 0 0.045 0"/></filter>
    <filter id="${id}-glow" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="${Math.max(4, W / 320)}"/></filter>
    <linearGradient id="${id}-c" x1="0" y1="1" x2="1" y2="0"><stop offset="0" stop-color="${C.monadPurple}"/><stop offset="1" stop-color="${C.lavender}"/></linearGradient>
    <linearGradient id="${id}-p" x1="1" y1="1" x2="0" y2="0"><stop offset="0" stop-color="${C.monadBerry}"/><stop offset="1" stop-color="#e0458f"/></linearGradient>
    <linearGradient id="${id}-chot" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="${C.offWhite}" stop-opacity="0.9"/><stop offset="0.55" stop-color="${C.offWhite}"/><stop offset="1" stop-color="${C.mint}"/></linearGradient>
    <linearGradient id="${id}-phot" x1="1" y1="0" x2="0" y2="0"><stop offset="0" stop-color="${C.offWhite}" stop-opacity="0.9"/><stop offset="0.55" stop-color="#ffd2b8"/><stop offset="1" stop-color="${C.ember}"/></linearGradient>
    <linearGradient id="${id}-burst" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${C.ember}"/><stop offset="1" stop-color="${C.lavender}"/></linearGradient>
    <radialGradient id="${id}-emberglow"><stop offset="0" stop-color="${C.ember}" stop-opacity="0.55"/><stop offset="1" stop-color="${C.ember}" stop-opacity="0"/></radialGradient>
    <linearGradient id="${id}-breakout" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="${C.lavender}"/><stop offset="0.5" stop-color="${C.monadPurple}"/><stop offset="1" stop-color="${C.mint}"/></linearGradient>
  </defs>
  <rect width="${W}" height="${H}" fill="url(#${id}-base)"/>
  <rect width="${W}" height="${H}" fill="url(#${id}-a1)"/><rect width="${W}" height="${H}" fill="url(#${id}-a2)"/>
  <rect width="${W}" height="${H}" fill="url(#${id}-a3)"/><rect width="${W}" height="${H}" fill="url(#${id}-a4)"/>
  <rect width="${W}" height="${H}" fill="url(#${id}-grid)" mask="url(#${id}-gridmask)"/>`;
}
const grain = (W, H, id) => `<rect width="${W}" height="${H}" filter="url(#${id}-grain)"/>`;

/**
 * Call and put fans meeting at a strike at (sx, sy). span: px from strike to each edge of the call fan; the put fan
 * gets putSpan. yScale: px per unit of strike value.
 */
function straddle(id, { sx, sy, span, putSpan = span, left = -20, right, yScale, callOp = 1, putOp = 0.75, count = 20, stroke = 1.4, dot = 9 }) {
  // Both fans run edge to edge (left, right: the art's bounds), so no curve starts mid-frame.
  const call = fan({ id, x0: left, x1: Math.max(right, sx + span), sx, k: span / 1.2, baseY: sy, yScale, count, stroke, opacity: callOp });
  const put = fan({ id, x0: left, x1: right, sx, k: putSpan / 0.62, baseY: sy, yScale, put: true, count, stroke, opacity: putOp });
  return `${put}${call}${strikeBurst(id, sx, sy, dot)}`;
}

function hero(W, H, id) {
  const portrait = H > W;
  const sx = W * (portrait ? 0.42 : 0.56);
  const sy = H * (portrait ? 0.78 : 0.8);
  return svg(
    W,
    H,
    `${ground(W, H, id, { aurora: [0.78, 0.12], strike: [sx / W, sy / H], grid: Math.round(W / 40) })}
    ${straddle(id, { sx, sy, right: W + 20, span: W - sx + W * 0.05, putSpan: sx * 2.6, yScale: portrait ? H * 0.5 : H * 0.62, putOp: 0.5, count: 22, stroke: W / 1500, dot: W / 190 })}
    ${grain(W, H, id)}`,
  );
}

function twitterHeader(W = 1500, H = 500, id = "tw") {
  const lx = 112;
  const sx = 930;
  const sy = 455;
  const tag = text(MEDIUM, "Uncapped options on Monad", 30, lx, 312, 0);
  const tag2 = text(MEDIUM, "Portfolio margin · ERC-20 longs · trades on Kuru", 21, lx, 352, 0);
  return svg(
    W,
    H,
    `${ground(W, H, id, { aurora: [0.8, 0.05], strike: [sx / W, sy / H], grid: 44 })}
    ${straddle(id, { sx, sy, right: W + 20, span: 640, putSpan: 380, yScale: 520, putOp: 0.4, count: 18, stroke: 1.3, dot: 8 })}
    ${markAt(`${id}-m`, lx - 6, 150, 110)}
    <path d="${text(BOLD, "optara", 104, lx + 124, 236, WORD_TRACK).d}" fill="${C.offWhite}"/>
    <path d="${tag.d}" fill="${C.offWhite}"/>
    <path d="${tag2.d}" fill="${C.mutedOnDark}"/>
    ${grain(W, H, id)}`,
  );
}

function ogImage(W = 1200, H = 630, id = "og") {
  const lx = 88;
  const sx = 800;
  const sy = 600;
  return svg(
    W,
    H,
    `${ground(W, H, id, { aurora: [0.85, 0.1], strike: [sx / W, sy / H], grid: 42 })}
    ${straddle(id, { sx, sy, right: W + 20, span: 460, putSpan: 2600, yScale: 640, putOp: 0.4, count: 16, stroke: 1.3, dot: 8 })}
    ${markAt(`${id}-m`, lx - 4, 76, 64)}
    <path d="${text(BOLD, "optara", 54, lx + 72, 124, WORD_TRACK).d}" fill="${C.offWhite}"/>
    <path d="${text(BOLD, "European options,", 70, lx, 330, -0.02).d}" fill="${C.offWhite}"/>
    <path d="${text(BOLD, "uncapped.", 70, lx, 410, -0.02).d}" fill="url(#${id}-breakout)"/>
    <path d="${text(MEDIUM, "Portfolio margin on Monad · ERC-20 longs on Kuru", 24, lx, 470, 0).d}" fill="${C.mutedOnDark}"/>
    ${grain(W, H, id)}`,
  );
}

/** Community banner (Discord server / Telegram / YouTube-safe centre). */
function communityBanner(W = 960, H = 540, id = "cb") {
  const ww = wordWidth(96);
  const total = 120 + 24 + ww;
  const x = (W - total) / 2;
  const tagline = "Uncapped options on Monad";
  const tw = text(MEDIUM, tagline, 28, 0, 0, 0).width;
  return svg(
    W,
    H,
    `${ground(W, H, id, { aurora: [0.5, 0.0], strike: [0.5, 0.95], grid: 40 })}
    ${straddle(id, { sx: W / 2, sy: H * 0.95, right: W + 20, span: W * 0.55, putSpan: W * 0.55, yScale: H * 0.36, callOp: 0.8, putOp: 0.6, count: 16, stroke: 1.2, dot: 7 })}
    ${markAt(`${id}-m`, x, 170, 120)}
    <path d="${text(BOLD, "optara", 96, x + 144, 262, WORD_TRACK).d}" fill="${C.offWhite}"/>
    <path d="${text(MEDIUM, tagline, 28, (W - tw) / 2, 352, 0).d}" fill="${C.mutedOnDark}"/>
    ${grain(W, H, id)}`,
  );
}

/** Quiet repeating tile: tiny payoff kinks with ember strikes, for section backgrounds. */
function patternTile(S = 240) {
  const k = (x, y, o) =>
    `<g opacity="${o}"><path d="M${x} ${y} h14 l16 -16" fill="none" stroke="${C.monadPurple}" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${x + 14}" cy="${y}" r="2.6" fill="${C.ember}"/></g>`;
  return svg(
    S,
    S,
    `<rect width="${S}" height="${S}" fill="${C.night}"/><path d="M${S} 0H0V${S}" fill="none" stroke="#fff" stroke-opacity="0.04"/>
    ${k(30, 80, 0.32)}${k(150, 200, 0.32)}${k(150, 80, 0.14)}${k(30, 200, 0.14)}`,
  );
}

// ------------------------------------------------------------------------------------------------ write
write("logo/optara-mark.svg", svg(64, 64, mark("m")));
write("logo/optara-mark-on-light.svg", svg(64, 64, mark("m", "light")));
write("logo/optara-mark-white.svg", svg(64, 64, mark("m", "white")));
write("logo/optara-mark-black.svg", svg(64, 64, mark("m", "black")));
write("logo/optara-app-icon.svg", appIcon(1024));
write("logo/optara-lockup-dark.svg", lockup("dark"));
write("logo/optara-lockup-light.svg", lockup("light"));
write("logo/optara-lockup-white.svg", lockup("white"));
write("logo/optara-lockup-black.svg", lockup("black"));
write("logo/optara-lockup-tagline-dark.svg", lockup("dark", { tag: true }));
write("logo/optara-lockup-tagline-light.svg", lockup("light", { tag: true }));
write("logo/optara-stacked-dark.svg", stacked("dark"));
write("logo/optara-stacked-light.svg", stacked("light"));
write("favicon/favicon.svg", appIcon(64, { radius: 0.22, scale: 0.86, id: "fv" }));
write("social/avatar.svg", avatar(1024));
write("social/twitter-header.svg", twitterHeader());
write("social/og-image.svg", ogImage());
write("social/community-banner.svg", communityBanner());
write("backgrounds/hero.svg", hero(2560, 1440, "hd"));
write("backgrounds/hero-mobile.svg", hero(1080, 1920, "hm"));
write("backgrounds/pattern-tile.svg", patternTile());
console.log("wrote brand assets to", OUT);
