/**
 * Generates src/abi.ts from deployments/abi/*.json (written by contract/script/export_abis.py) as `as const`
 * literals, so viem infers argument and return types. `--check` fails if the file is out of date (CI).
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const root = fileURLToPath(new URL("../..", import.meta.url));
const abiDir = join(root, "deployments", "abi");
const out = fileURLToPath(new URL("../src/abi.ts", import.meta.url));

const camel = (name: string) => name[0]!.toLowerCase() + name.slice(1);

const files = readdirSync(abiDir)
  .filter((f) => f.endsWith(".json"))
  .sort();
let text = "// Generated by scripts/gen-abi.ts from deployments/abi. Do not edit.\n";
for (const f of files) {
  const name = f.replace(/\.json$/, "");
  const abi = JSON.parse(readFileSync(join(abiDir, f), "utf8"));
  text += `\nexport const ${camel(name)}Abi = ${JSON.stringify(abi)} as const;\n`;
}

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(out, "utf8");
  } catch {}
  if (current !== text) {
    console.error("sdk/src/abi.ts is out of date: run `pnpm --filter @optara/sdk gen:abi`");
    process.exit(1);
  }
  console.log(`${files.length} ABIs up to date`);
} else {
  writeFileSync(out, text);
  console.log(`wrote ${files.length} ABIs to sdk/src/abi.ts`);
}
