/**
 * The Envio config for a deployment (DEPLOYMENT.md §3.2 manifest). Contracts, events and handlers are the same on
 * every network; only the chain, addresses and data source differ. Local and e2e chains use RPC (ENVIO_RPC_URL);
 * Monad uses HyperSync (ENVIO_API_TOKEN) with the RPC as fallback.
 */
import type { Manifest, ModuleName } from "@optara/sdk";

const EVENTS: Partial<Record<ModuleName | "ExternalOptionWrapper", string[]>> = {
  ProtocolControl: ["RoleGranted", "RoleRevoked", "Paused", "Unpaused", "ProductCloseOnlySet"],
  OptionSeriesRegistry: ["ProductApproved", "ProductEnabled", "GroupCreated", "SeriesCreated"],
  SubAccounts: ["SubAccountCreated", "OperatorSet", "CashUpdated", "BalanceUpdated", "ParticipantsUpdated"],
  OptionClearing: ["ExternalLongMinted"],
  LiveSpotOracle: ["SpotUpdated"],
  VolSurfaceOracle: ["SurfaceAccepted", "NodeProven", "EmergencyModeSet", "PublisherAdded", "PublisherRemoved", "QuorumSet"],
  PortfolioRiskManager: ["ProductRiskSetAssigned", "ProductShortCapSet"],
  InsuranceFund: ["InsuranceDeposited", "InsurancePaid"],
  FeeController: ["SellerFeeCharged", "BuyerFeeCharged", "FeeSplit", "KeeperRewardPaid", "MinimumsSet"],
  LiquidationModule: ["AuctionStarted", "SliceLiquidated", "WrapperLiquidated", "AuctionEnded", "BadDebtCovered"],
  SettlementWindow: ["GroupFinalized", "OracleStalled", "AccountSettled", "RecoveryRatioSet", "SettlementClaimed", "WrapperRedeemed", "DustSwept"],
  VenueRegistry: ["MarketRegistered", "MarketStatusSet"],
  VenueRouter: ["VenueTrade"],
  ExternalOptionWrapper: ["Transfer"],
};

const UPGRADE_ADMIN_EVENTS = ["UpgradeScheduled", "UpgradeExecuted", "UpgradeCancelled", "ImplementationAllowed", "GovernanceTransferred"];

export function configYaml(m: Manifest, source: string): string {
  // Monad uses HyperSync, except a LOCAL FORK of Monad (network "local", or any manifest served by a local RPC):
  // it shares chain id 143, but its blocks after the fork exist only on the local node.
  const localFork = m.network === "local" || /^(e2e|fe2e|kurutest|rehearsal)/.test(m.network);
  const hypersync = (m.chainId === 143 || m.chainId === 10143) && !localFork;
  const lines = [
    "# yaml-language-server: $schema=./node_modules/envio/evm.schema.json",
    `# Generated by scripts/gen-config.ts from ${source}. Do not edit.`,
    "name: optara",
    "description: Optara PM indexer (INDEXER_AND_KEEPERS.md §1)",
    "schema: schema.graphql",
    "disable_default_cross_chain: true",
    "rollback_on_reorg: true",
    "contracts:",
  ];
  const contracts = [...Object.keys(EVENTS), "UpgradeAdmin"];
  for (const c of contracts) {
    lines.push(`  - name: ${c}`, `    abi_file_path: ../deployments/abi/${c}.json`, "    events:");
    for (const e of c === "UpgradeAdmin" ? UPGRADE_ADMIN_EVENTS : EVENTS[c as keyof typeof EVENTS]!) lines.push(`      - event: ${e}`);
  }
  lines.push("chains:", `  - id: ${m.chainId}`, `    start_block: ${m.deployedAtBlock}`);
  if (hypersync) {
    const rpc = m.chainId === 143 ? "https://rpc.monad.xyz" : "https://testnet-rpc.monad.xyz";
    lines.push("    rpc:", `      - url: \${ENVIO_RPC_URL:-${rpc}}`, "        for: fallback", "        interval_ceiling: 100 # public Monad RPC: eth_getLogs over at most 100 blocks");
  } else {
    lines.push("    rpc:", "      - url: ${ENVIO_RPC_URL:-http://127.0.0.1:8545}", "        for: sync", "    max_reorg_depth: 64");
  }
  lines.push("    contracts:");
  for (const c of contracts) {
    if (c === "ExternalOptionWrapper") {
      lines.push("      - name: ExternalOptionWrapper # registered from SeriesCreated");
      continue;
    }
    const address = c === "UpgradeAdmin" ? m.upgradeAdmin : m.proxies[c as ModuleName].proxy;
    lines.push(`      - name: ${c}`, `        address: "${address}"`);
  }
  return lines.join("\n") + "\n";
}
