"""Export ABIs of the deployed Optara contracts to ../deployments/abi (JSON and typed TypeScript).

Run after `forge build`: python3 script/export_abis.py
The indexer, the frontend and the separate SDK repo consume these files; none of them retype ABIs by hand.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(HERE, "..", "out")
DEST = os.path.join(HERE, "..", "..", "deployments", "abi")

CONTRACTS = {
    "OptaraCore": "OptaraCore.sol/OptaraCore.json",
    "OptaraConfig": "OptaraConfig.sol/OptaraConfig.json",
    "OracleRegistry": "OracleRegistry.sol/OracleRegistry.json",
    "ChainlinkSettlementAdapter": "ChainlinkSettlementAdapter.sol/ChainlinkSettlementAdapter.json",
    "SeriesFactory": "SeriesFactory.sol/SeriesFactory.json",
    "OptionToken": "OptionToken.sol/OptionToken.json",
    "AggregatorV3": "IAggregatorV3.sol/IAggregatorV3.json",
    "ERC20": "ERC20.sol/ERC20.json",
}


def camel(name):
    return name[0].lower() + name[1:]


def main():
    os.makedirs(DEST, exist_ok=True)
    index = []
    for name, rel in CONTRACTS.items():
        with open(os.path.join(OUT_DIR, rel)) as f:
            abi = json.load(f)["abi"]
        with open(os.path.join(DEST, f"{name}.json"), "w") as f:
            json.dump(abi, f, indent=1)
        with open(os.path.join(DEST, f"{name}.ts"), "w") as f:
            f.write("// Generated by contract/script/export_abis.py. Do not edit.\n")
            f.write(f"export const {camel(name)}Abi = {json.dumps(abi, indent=1)} as const;\n")
        index.append(f'export {{ {camel(name)}Abi }} from "./{name}";')
    with open(os.path.join(DEST, "index.ts"), "w") as f:
        f.write("// Generated by contract/script/export_abis.py. Do not edit.\n" + "\n".join(index) + "\n")
    print(f"exported {len(CONTRACTS)} ABIs to {os.path.normpath(DEST)}")


if __name__ == "__main__":
    main()
