// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// Shared constants and types. See simple-workflow/contracts.md.

uint256 constant PRICE_SCALE = 1e18;
uint256 constant BPS_SCALE = 10_000;

// Hard fee caps. Compile-time constants: no role can exceed them.
uint16 constant MAX_MINT_FEE_BPS = 100; // 1.00%
uint16 constant MAX_EXERCISE_FEE_BPS = 100; // 1.00%

// Series creation limits. Fixed in code so no user can choose them.
uint64 constant MIN_EXPIRY_DELAY = 1 hours;
uint64 constant MAX_EXPIRY_DELAY = 30 days;
// Expiry must fall at this offset into a UTC day (08:00 UTC).
uint64 constant EXPIRY_SLOT_OFFSET = 8 hours;
uint8 constant OPTION_DECIMALS = 18;
// Minimum mint size: 0.01 option. Mint only.
uint256 constant MIN_OPTION_AMOUNT = 1e16;

// Role ids. There are exactly two roles, held on the factory.
bytes32 constant ADMIN_ROLE = 0x00; // OpenZeppelin DEFAULT_ADMIN_ROLE
bytes32 constant PAUSER_ROLE = keccak256("PAUSER_ROLE");

enum OptionType {
    CALL,
    PUT
}

struct FeeConfig {
    uint16 mintFeeBps;
    uint16 exerciseFeeBps;
}

/// The ONLY things a user chooses when creating a series.
struct CreateSeriesParams {
    OptionType optionType;
    address underlying;
    address quote;
    uint256 strikePrice; // PRICE_SCALE: whole quote per whole underlying, times 1e18
    uint64 expiry; // unix seconds, at most 30 days out, on the 08:00 UTC slot
    address chainlinkFeed; // must equal the ADMIN-approved feed for this pair
}

/// Set by ADMIN for each (underlying, quote) pair. Users cannot choose these.
struct PairConfig {
    address feed; // the one approved Chainlink feed, address(0) = pair disabled
    uint32 maxChainlinkAgeAtExpiry; // seconds, heartbeat plus a buffer
    uint256 strikeStep; // strike must be a multiple of this, PRICE_SCALE units
}

/// The complete, fixed definition of a series, assembled by the factory and passed to the vault.
struct SeriesConfig {
    OptionType optionType;
    address underlying;
    address quote;
    uint256 strikePrice;
    uint64 expiry;
    uint256 contractSize; // 10 ** underlyingDecimals: one whole underlying per option
    uint8 optionDecimals; // OPTION_DECIMALS
    uint256 minOptionAmount; // MIN_OPTION_AMOUNT
    uint256 maxTotalShortAmount; // snapshot of the underlying's cap, 0 = uncapped
    address chainlinkFeed;
    uint32 maxChainlinkAgeAtExpiry; // snapshot of the pair's value
    string name; // generated by the factory
    string symbol; // generated by the factory
}

/// What the vault reports about itself. Read by the guard and the frontend.
struct SeriesInfo {
    bytes32 seriesId;
    OptionType optionType;
    address underlying;
    address quote;
    address collateralAsset;
    uint256 strikePrice;
    uint64 expiry;
    uint256 contractSize;
    uint8 optionDecimals;
    uint256 minOptionAmount;
    uint256 maxTotalShortAmount;
    address chainlinkFeed;
    uint8 feedDecimals;
    uint32 maxChainlinkAgeAtExpiry;
    uint256 optionScale;
    uint256 uqScale;
    uint256 collateralPerOption;
    uint16 mintFeeBps;
    uint16 exerciseFeeBps;
}

struct SettlementProof {
    uint80 chainlinkRoundId; // the round in force at expiry
    uint80 chainlinkNextRoundId; // its immediate successor
}
